### ISSUE TITLE
Abstract (v1.1.0 draft 3)

### ISSUE THREAD

**Issue by hlflanagan** [KantaraInitiative/CISWG#103]
"A Consent Receipt is the focus for an open standard, because it is a machine readable record of a consent that is converted into a (re usable) human readable format." The logic here doesn't parse. The machine readability of a record has nothing to do with the specification being the focus of an open standard. If you want to emphasize that this is an open standard, something like "A Consent Receipt is the focus for an open standard because of the need for a ubiquitous, machine-readable record of consent."

**Comment by smartopian** [comment]
+1
