### ISSUE TITLE
On Behalf field - 

### ISSUE THREAD

**Issue by smartopian** [KantaraInitiative/CISWG#110]
in the UK Data Protection Act - on Behalf  - when clicked - what does this mean?  is it that the Controller listed is a processor on behalf of another data controller?  i.e. 'processed on behalf of'

In the GDPR: 
Its clear that this is a critical field for presenting the liability of data processing, so this should guide our decision here.

-  If this is clicked , does it makes sense to then list or link to the  the data controller name, contact information, and service?  or - is it the reverse, -  the DC contact information is presented with the 'On Behalf' selection and  then should the processors name and controller information is added?  perhaps with a link to the service? 

After thinking about this, it seems that the most important information for a consent receipt is the privacy contact information and the jurisdiction of the DC/Processor.     What seems to be missing is the - is data transferred internationally field?   -  Which it seems would also be important to include with the contact information.    

Would be good to know how others have dealt with this?   

Some GDPR research on this reveals:
--> recital (74) (79) (80 - which states a representative should be in the EU and act on behalf of DC out of the EU)

Article 4 - Definitions (8) --->  ‘processor’ means a natural or legal person, public authority, agency or other body which processes personal data **on behalf** of the controller;

Article 28 - is all about processors - (5) is an important clause to bring up, as it sheds light on the role of this specification in GDPR -In that a receipt is proof of adherence to a code of conduct  

-"Adherence of a processor to an approved code of conduct as referred to in Article 40 or an approved certification mechanism as referred to in Article 42 may be used as an element by which to demonstrate sufficient guarantees as referred to in paragraphs 1 and 4 of this Article." 
and
 " Each processor and, where applicable, the processor's representative shall maintain a record of all categories of. processing activities carried out on behalf of a controller, containing: "

My recommendation -   "on behalf"  refers to listing the DC, jurisdiction, Company Name, Service Name and Privacy Contact/DPO at the minimum.

**Comment by dturnerx** [comment]
@smartopian On behalf is currently defined as: 

"A PII Processor acting on behalf of a PII Controller or PII Processor. 
For example, a third-party analytics service would be a PII Processor on behalf of the PII Controller, or a site operator acting on behalf of the PII   Controller."

Your proposal will completely redefine the field. Is that the right thing to do in a .1 release?

**Comment by smartopian** [comment]
Not sure its a complete redefinition - Right now its not clear - as we are now tackling DC contact info etc it would be great to make this clear in the specification 

I.e -  Does on behalf meant the DC controller contact is the PII Processor contact?  or does it meant that we need to add PII Process Contact ?  

What is clear, is that 	on behalf does not mean 3rd party in terms of GDPR.  So this should change at a minimum.

**Comment by dturnerx** [comment]
I interpret the current definition to mean On Behalf is a place to put information when the PII Controller is acting as an agent (or intermediary, proxy, etc) for some other party. That party may be a PII Processor, another PII Controller, or some other "3rd party". 

We could suggest what types of information to include while emphasizing that actual requirements are defined by their relevant jurisdictions or domains.

**Comment by smartopian** [comment]
thats interesting - and does make sense - the data controller information is then appended with a field to indicate that organisations acts on behalf  of the DC.   

At the moment, this field, originating from the 1998 Data Protection Act - and I think this field is the most poorly defined/applied field in the history of UK/EU privacy legislation..  

Here is an excerpt from the DPA

" data controller” means, subject to subsection (4), a person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed;
“data processor”, in relation to personal data, means any person (other than an employee of the data controller) who processes the data on behalf of the data controller;
“data subject” means an individual who is the subject of personal data;
“personal data” means data which relate to a living individual who can be identified—
(a)from those data, or
(b)from those data and other information which is in the possession of, or is likely to come into the possession of, the data controller,"

**Comment by smartopian** [comment]
Another reference from the Data Protection Act: (which is the current law in the UK)
 
(Note -- there are 31 'on-behalf' references in the DPA, so I picked out the notification requirement, which is for Data Controllers - not processors ) 
 
**Notification by data controllers**

16 Preliminary.

(1)In this Part “the registrable particulars”, in relation to a data controller, means—
(a)his name and address,
(b)if he has nominated a representative for the purposes of this Act, the name and address of the representative,
(c)a description of the personal data being or to be processed by **or on behalf of the data controller** and of the category or categories of data subject to which they relate,
(d)a description of the purpose or purposes for which the data are being or are to be processed,
(e)a description of any recipient or recipients to whom the data controller intends or may wish to disclose the data,
(f)the names, or a description of, any countries or territories outside the European Economic Area to which the data controller directly or indirectly transfers, or intends or may wish directly or indirectly to transfer, the data,

**Comment by PrivacyCDN** [comment]
See #95
