### ISSUE TITLE
Proposal to merge and reformat tables 1 & 2

### ISSUE THREAD

**Issue by dturnerx** [KantaraInitiative/CISWG#113]
We have received many comments about the current use of two tables to present the CR field information. The attached proposal merges the two tables and uses a new layout that includes all the same information. 

The new layout uses a format similar to what is used in many other specs including OAuth, OIDC, and UMA. 

[Field definition layout.docx](https://github.com/KantaraInitiative/CISWG/files/1398673/Field.definition.layout.docx)

**Comment by PrivacyCDN** [comment]
Done
