### ISSUE TITLE
CR v1.1 - Field Data Type Error - Effecting the view-ability of the receipt 

### ISSUE THREAD

**Issue by MLHart** [KantaraInitiative/CISWG#118]
The result is that there is no PII. Controller name in a receipt produced spec an viewed in the viewer.
From OC -viewer conformance input - The spec does not clearly differentiate between child objects (or values) and their parents. Thus the spec defines piiController as an array. What it then does is list a number of other fields WITHOUT indicating that they are a grouped object that is what is in the array.
From what I can tell 4.4.2 (line 319) refers to an array, this array is comprised of objects (i.e. more than one field) which is made of 4.4.3 - 4.4.9 (lines 323 to 358).
However in the spec there are simply a long list of fields with no indication as to which are children of others. 4.4.10 (line 359) for example, has no indication as to whether it is a part of the piiController object (4.4.3 - 4.4.9) or is a sibling of piiControllers (4.4.2)
Solution
piiControllers - should be an array of piiController objects - and this should be explicity stated in the spec
piiController should not be a string, neither should service or purpose - these fields should also be changed to  objects with object schema definitions added .. Might also have a name field (or description field in the object that is a string.

**Comment by andrewhughes3000** [comment]
This was an issue parsing the Schema (it was treated like an example). On further discussion with CIS WG, close this issue with no change required.
