### ISSUE TITLE
Should MVCR include an option for Parental Consent? (add item for v.2)

### ISSUE THREAD

**Issue by smartopian** [KantaraInitiative/CISWG#13]
This might be a check box that can indicate that this is a parental consent receipt -  This would then need to include childs identity and a subset MVCR for the chidren consent receipt.

**Comment by PrivacyCDN** [comment]
Mark;

This is a subset of the general question about capacity for consent, which means different things in different contexts. There was a recent conversation about this in the UMA workgroup and it seems possible that this might be a joint effort where we can take guidance from the UMA legal subgroup. In the spirit of “minimum viable” can I suggest that we add language to the spec description that says something like, “This specification assumes that the PII subject has the capacity and authority to provide consent."

Sincerely,
John Wunderlich
(@PrivacyCDN)

 http://privacybydesign.ca/ http://privacybydesign.ca/

 http://privacybydesign.ca/Privacist & PbD Ambassador http://privacybydesign.ca/

> On Feb 18, 2016, at 10:24, Mark Lizar notifications@github.com wrote:
> 
> This might be a check box that can indicate that this is a parental consent receipt - This would then need to include childs identity and a subset MVCR for the chidren consent receipt.
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/KantaraInitiative/CISWG/issues/13.

## 

This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. If you are not the intended recipient 
you are notified that disclosing, copying, distributing or taking any 
action in reliance on the contents of this information is strictly 
prohibited.

**Comment by smartopian** [comment]
should there be an - on behalf of, field in their for the PI Principal -  just like there is for the Data Controller. ?

**Comment by smartopian** [comment]
Action is taken and put on the list for V.2 --> find tabled issues here https://kantarainitiative.org/confluence/display/infosharing/Consent+Receipt+V2+Agenda+Items
