### ISSUE TITLE
Remove Json Fields from the  MUST category  and move to Appendix 

### ISSUE THREAD

**Issue by smartopian** [KantaraInitiative/CISWG#15]
This issue is weather or not to remove JSON fields from the Specification

On the CISWG mailing list - there has been issues raised that this shouldn't be in the MVCR as a mandatory
**For**:
- this is raised the issue that this is a core reason for making the specification, it makes a possible standard viable at scale and usable by all the standards orgs that interested in this. 
- this is the technical to policy bridging item, 
- doing this enables syncs with UMA, COEL, ID-Event - ISO efforts 
- this has already found consensus   in v0.7 (Alpha) 

**Against**
 this should be technology agnostic and usable on paper and should be in the appendix
technical side not needed for policy proof to regulator
makes this flexible so that anyone can make receipt with the core fields and be compliant with the specification (AKA - Doesnt need JSON

**Comment by PrivacyCDN** [comment]
If we do end up moving the JSON fields to an Appendix, it seems to me that we should make clear in the 1.0 version that the Appendix is “A” specification compliant technical implementation, not “THE” specification compliant technical implementation.

> On Feb 21, 2016, at 14:59, Mark Lizar notifications@github.com wrote:
> 
> This issue is weather or not to remove JSON fields from the Specification
> 
> On the CISWG mailing list - there has been issues raised that this shouldn't be in the MVCR as a mandatory
> For:
> 
> this is raised the issue that this is a core reason for making the specification, it makes a possible standard viable at scale and usable by all the standards orgs that interested in this.
> this is the technical to policy bridging item,
> doing this enables syncs with UMA, COEL, ID-Event - ISO efforts
> this has already found consensus in v0.7 (Alpha)
> Against
> this should be technology agnostic and usable on paper and should be in the appendix
> technical side not needed for policy proof to regulator
> makes this flexible so that anyone can make receipt with the core fields and be compliant with the specification (AKA - Doesnt need JSON
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/KantaraInitiative/CISWG/issues/15.

## 

This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. If you are not the intended recipient 
you are notified that disclosing, copying, distributing or taking any 
action in reliance on the contents of this information is strictly 
prohibited.

**Comment by smartopian** [comment]
Had some good input from others running standards efforts on this point. 
1.  not having JSON fields as a must would make the specification less OPEN,
2. less interoperable
3. less usable by other efforts
4. more likely not be adopted in a uniform way

**Comment by smartopian** [comment]
I also agree, that a key benefit to Kantara and a core reason why we are creating a specification rather than a policy document is so that we can bind technical and legal fields  together

**Comment by PrivacyCDN** [comment]
My responses to the bare assertions below.

> On Feb 22, 2016, at 13:26, Mark Lizar notifications@github.com wrote:
> 
> Had some good input from others running standards efforts on this point.
> 1. not having JSON fields as a must would make the specification less OPEN,
> 
> Having JSON fields as a MUST means that if Bob produced a PDF with all the fields of a Consent Receipt, it would not be compliant. Seems to me that requiring people have to have the wherewithal and technical knowledge to put in the JSON fields bars many small entities from using the consent receipt in a compliant way. That hardly strikes me as more open. What strikes me as more open is creating operational definitions of the information necessary for a consent receipt to enable anyone to provide that information with the tools that they have handy.
> 2. less interoperable
> 
> Having the JSON fields there essentially acts as a strong recommendation and allows entities that want to interoperate to do so, but interoperability on the back end between vendors or PII Controllers and PII Processors doesn’t seem to me to be part of the requirements of the MVCR.
> 1. less usable by other efforts
> 
> See response to point 1 above. By providing direction on the information required, but leaving the modality and presentation to the web site providers and to the market to provide solutions seems to me to be more usable.
> 4. more likely not be adopted in a uniform way
> 
> If the information in the consent receipts that people provide fulfills the requirements set out in the spec that is, by definition, uniform in that all uniformly provide the minimum information to the PII subject required by the specification. Or am I missing something.
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/KantaraInitiative/CISWG/issues/15#issuecomment-187306179.

## 

This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. If you are not the intended recipient 
you are notified that disclosing, copying, distributing or taking any 
action in reliance on the contents of this information is strictly 
prohibited.

**Comment by smartopian** [comment]
i think we have yet to get to the topic of rendering the consent receipt. if the receipt is rendered as a pdf does it make it non-compliant with the MVCR specification?  maybe, is it still compliant with legal requirements -->  yes.  
We could and probably should add to the spec or guidance something about rendering the receipt.  In this guidance we can put tha using the JSON fields in only required for implementations of a certain type, and that rendering the receipt, can be done in any fashion, but recommended in x, y, z, formats.

**Comment by PrivacyCDN** [comment]
It seems to me that the phrase, “…rendering the consent receipt” presupposes the conclusion that the ‘real’ consent receipt is the electronic format. I don’t think that there is consensus on that. I had thought we had consensus that the consent receipt is delivered when the information is presented to the PII subject be it as a webpage, a pdf, or an electronic file. In other words, we are agnostic on how it gets to the point of being presented or rendered.

To your point of guidance about rendering, you will note that in my tabular update to the github spec, I have added, below each section’s table an example of what that section could look like.

I also thought that there was consensus, or at least a lack of disagreement, that whether the PII subject chooses to read, download, print or otherwise retain the receipt is out of scope of the MVCR. That the receipt was offered or presented to the Alice, and that Bob retains his copy - or some other equivalent audit event - allows Bob to make an argument that he was/is compliant with his particular jurisdiction in the event of a complaint or an audit. Whether he is, or isn’t compliant, will of course be subject to a decision by a competent authority in each jurisdiction. Parenthetically this makes Section 6 - the optional fields - potentially crucial to enable Bob to be compliant with what he believes his requirements are.

JW

> On Feb 22, 2016, at 13:46, Mark Lizar notifications@github.com wrote:
> 
> i think we have yet to get to the topic of rendering the consent receipt. if the receipt is rendered as a pdf does it make it non-compliant with the MVCR specification? maybe, is it still compliant with legal requirements --> yes.
> 
> We could and probably should add to the spec or guidance something about rendering the receipt. In this guidance we can put tha using the JSON fields in only required for implementations of a certain type, and that rendering the receipt, can be done in any fashion, but recommended in x, y, z, formats.
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/KantaraInitiative/CISWG/issues/15#issuecomment-187314370.

## 

This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. If you are not the intended recipient 
you are notified that disclosing, copying, distributing or taking any 
action in reliance on the contents of this information is strictly 
prohibited.

**Comment by smartopian** [comment]
The suppositions that the receipt will be created in an electronic format is what the key 'closed consent' problem. Opening Consent, was all about solving this.  In that it can be aggregated by the individual so they can see their consents, one by one, or on aggregate. 

This was presented at the W3C conference in 2012 by Reuben and I - and was what kicked off the start of this particular effort in Open Notice, which then led to Kantara - see w3c paper 
https://www.w3.org/2012/dnt-ws/position-papers/23.pdf
"The current notice infrastructure is “closed.” By this we mean that notices are
not automatically findable and systematically usable. "

also see usable consent papers -https://www.cylab.cmu.edu/news_events/events/fopnac/pdfs/lizar.pdf
-- As for point two.. - providing guidance on the ways, or how to present the consent receipt, I agree might not be in the spec, but would should be added to the knowledge base and be presented with the spec.

**Comment by PrivacyCDN** [comment]
Interoperable electronic consent receipts make sense as an end state spec, but it seems to me that the necessary precursor is defining the information contained therein and socializing that standard in a way that enables even the most tech newbie to generate one based on the information defined in the standard - AKA MVCR.  

Sent from Outlook Mobile. Yes, it works with gmail.

```
_____________________________
```

**Comment by smartopian** [comment]
It seems to me that what you are describing for a newbie is a policy specification for how to use the MVCR spec.  As the goal has always been to make this specification.

From this perspective the specification you are describing,  Is a policy specification, recommendation, or best practice.  Perhaps, something like a trust mark.  It doesnt  makes sense to make  a technical specification for this policy standard at an organisation like Kantara.  

I suppose if the only objective output of this standard was to create something for companies to illustrate compliance, then the policy fields, by themselves,  would provide this fundamental benefit.  A benefit for  creating a trust mark perhaps.  

But, the point of this specification, is to provide also the framework to make consent usable for people. aka - electronically and legally.  AKA -  consent management   

Usability for people being the operable reason this effort has been gestated in Kantara.   From the outset the purpose has been to bridge the gap with people and identity based management of information sharing.   A discourse that has evolved inch by inch in Kantara  into what it is now for 6+ years.  

I think the idea you have about the non-technical policy version is extremely valuable.   I think that this version perhaps is very valuable because  the receipt can be implemented by anyone.  So, from a policy/standard point of view.

 I would tend to agree that the JSON field names not being a MUST for making any output of  receipt would be good  guidance for the the MVCR specification if its aim was to meet legal policy requirements.

**Comment by smartopian** [comment]
this thread seems to boil down to two questions: 

Is JSON a must or should they be in a knowledge base? 
Are the data fields a must or should they be in a knowledge base? 

But, After last call its clear that what is the issue is more general - what are the MUSTs and what is meant by the compliant use of the MVCR?   (which is a preceding conversation)  see #17 .   

(Note: I think that the data and json fields should stay in for v0.8 and that we can wait to determine them a must or not once we have the MVCR compliance requierments/description agreed.  )

**Comment by smartopian** [comment]
So, in the end, the data fields and data type columns have stayed in the specification, but, the json examples have moved to the Appendix.   There is the question of how this appendix is moved forward. should it be updated?  how do we do this ?  when should it be done by?  should we update the consent receipt generator?  Action for the WG

**Comment by smartopian** [comment]
JSON moved to Appendix
