### ISSUE TITLE
What is  the 'criteria' for Compliance and Validation of the MVCR? 

### ISSUE THREAD

**Issue by smartopian** [KantaraInitiative/CISWG#17]
****\* Strawman ***\* 
MVCR Objectives: Open Consent Objective, Validation,  Interoperability: Should these be 

The MVCR is specification to open consent. 
(Note: This is a straw-man intro for compliance, legal policy and inter-operability)

Open consent by:
- The grantee obtains a record of consent at point of consent so as to be contextually usable
- The grantee can use the receipt to communicate with the data controller about the consent, 
- The consent receipt can be used by the grantee (data subject) and the grantor (Data Controller) to prove consent
## Validation:
- The consent receipt can be used to see if the contact and data controller fields are responsive to the minimum legal level in order to be valid for contextual use.
- The policy fields have minimum requirements for the data put into them to be valid and 
- Must be proportionally linked. I.e. if the receipt is written then the piece of paper then phone number and address are linked via paper.  If the context is digital than the contact information and address should be linked and viewable real time.

**Comment by PrivacyCDN** [comment]
MVCR Objective: The minimum set of information that for most instance of
Alice and Bob, will enable Bob to tell Alice about his privacy policy, the
jurisdiction that sets out his legal data protection requirements and what
information about her was collected, for what purposes and whether or not
it is being disclosed to others.

That’s it, that’s all. Compliance, legal policy, and inter-operability are
all road map items.

Sincerely,
John Wunderlich
@PrivacyCDN

Call: +1 (647) 669-4749
eMail: john@wunderlich.ca

On 29 February 2016 at 13:42, Mark Lizar notifications@github.com wrote:

> ****\* Strawman ****
> MVCR Objectives: Open Consent Objective, Validation, Interoperability:
> Should these be
> 
> The MVCR is specification to open consent.
> (Note: This is a straw-man intro for compliance, legal policy and
> inter-operability)
> 
> Open consent by:
> - The grantee obtains a record of consent at point of consent so as to
>   be contextually usable
> - The grantee can use the receipt to communicate with the data
>   controller about the consent,
> - The consent receipt can be used by the grantee (data subject) and
>   the grantor (Data Controller) to prove consent
> 
> Validation:
> - The consent receipt can be used to see if the contact and data
>   controller fields are responsive to the minimum legal level in order to be
>   valid for contextual use.
> - The policy fields have minimum requirements for the data put into
>   them to be valid and
> - Must be proportionally linked. I.e. if the receipt is written then
>   the piece of paper then phone number and address are linked via paper. If
>   the context is digital than the contact information and address should be
>   linked and viewable real time.
> 
> Inter-operability:
> - There is a project kit for finding the legal reference and notice
>   requirements for each field relevant to your jurisdiction and legal context
>   so that the receipt can scale. (Knowledge Base Link)
> - The fields themselves provide the minimum common consent policy
>   template and the use of this specification as standard to make it and Open
>   Consent receipt. Requiring the order of the fields to mandatory for the
>   spec implementation to be compliant.
> - (note: The receipt is intended to perform if valid and responsive
>   contact information is provided. Purpose, sharing policy links, frameworks
>   are intended to be proportional to technology used to collect the PII. In
>   so much that this MVCR is designed so that it can be used in a way that is
>   an inter-operable as possible.
> - Optional fields are then listed to provide commonly required basic
>   consent functionality, compliance and notice inter-operability across a
>   diverse range of requirements.
> 
> ##Legal Policy
> The receipt is a legal policy document in so much that is designed to be a
> host to consent notice requirements and be used to certify trust based
> frameworks.
> 
> It achieves this by linking to required open notice requirements.
> Mandatory links, proportional to the context of consent, must be recorded
> in the receipt so that it can be contextually relevant and scale to the
> widest array of contexts. (I.e. icons, trust frameworks, identity
> frameworks, reputation frameworks)
> 
> The MVCR is intended to be measurable as a basis for consent frameworks
> by, being a versatile consent receipt, that is scalable for market and
> cross domain self-regulation of consent. (?)
> 
> All components of the receipt are then usable, in any order post consent,
> to create iterative updates to the consent. Maintaining a current 'state'
> of consent authorisation policy across contexts.
> (note: should the MVCR - refer to a record, and the iterative updates
> referred to as receipts?
> (note: proportionality needs to be defined)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/KantaraInitiative/CISWG/issues/17.

## 

This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. If you are not the intended recipient 
you are notified that disclosing, copying, distributing or taking any 
action in reliance on the contents of this information is strictly 
prohibited.

**Comment by smartopian** [comment]
The minimum set of information at what level of quality?   I.e. linked? 

Here is the minimum set.. this should be the intro
1. Purpose
2. \- Data Controller and DC Contact information,
3. \- Jurisidiction, Time and date, 
4. \- Sensitive Data (Y/N)
5. \- Sharing with third paries (Y/N)
6. \- Extensions -
