### ISSUE TITLE
Adding Inter-op section to MVCR  or Knowledge base? 

### ISSUE THREAD

**Issue by smartopian** [KantaraInitiative/CISWG#18]
Should we make inter-op a part of the guidance for the Spec or an objective of the specification? 

Where should Inter-op go? 
## Inter-op
- There is a project kit for finding the legal reference and notice requirements for each field relevant to your jurisdiction and legal context so that the receipt can scale.  (Knowledge Base Link)
- The fields themselves provide the minimum common consent policy template and the use of this specification as standard to make it and Open Consent receipt. Requiring the order of the fields to mandatory for the spec implementation to be compliant. 
- (note: The receipt is intended to perform if valid and responsive contact information is provided. Purpose, sharing policy links, frameworks are intended to be proportional to technology used to collect the PII.  In so much that this MVCR is designed so that it can be used in a way that is an inter-operable as possible. 
- Optional fields are then listed to provide commonly required basic consent functionality, compliance and notice inter-operability across a diverse range of requirements.

**Comment by PrivacyCDN** [comment]
​Not part of MVRC. Parking lot for full version consideration.​

Sincerely,
John Wunderlich
@PrivacyCDN

Call: +1 (647) 669-4749
eMail: john@wunderlich.ca

On 29 February 2016 at 13:54, Mark Lizar notifications@github.com wrote:

> Should we make inter-op a part of the guidance for the Spec or an
> objective of the specification?
> 
> Where should Inter-op go?
> Inter-op
> - There is a project kit for finding the legal reference and notice
>   requirements for each field relevant to your jurisdiction and legal context
>   so that the receipt can scale. (Knowledge Base Link)
> - The fields themselves provide the minimum common consent policy
>   template and the use of this specification as standard to make it and Open
>   Consent receipt. Requiring the order of the fields to mandatory for the
>   spec implementation to be compliant.
> - (note: The receipt is intended to perform if valid and responsive
>   contact information is provided. Purpose, sharing policy links, frameworks
>   are intended to be proportional to technology used to collect the PII. In
>   so much that this MVCR is designed so that it can be used in a way that is
>   an inter-operable as possible.
> - Optional fields are then listed to provide commonly required basic
>   consent functionality, compliance and notice inter-operability across a
>   diverse range of requirements.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/KantaraInitiative/CISWG/issues/18.

## 

This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. If you are not the intended recipient 
you are notified that disclosing, copying, distributing or taking any 
action in reliance on the contents of this information is strictly 
prohibited.

**Comment by smartopian** [comment]
Added to V.2 advanced issues for when
