### ISSUE TITLE
Adding Legal Policy section to Interoperability - Use of MVCR for policy:  (or for use with legal policy) 

### ISSUE THREAD

**Issue by smartopian** [KantaraInitiative/CISWG#19]
## Legal Policy

The receipt is a legal policy document in so much that is designed to be a host to consent notice requirements and be used to certify trust based frameworks.  

It achieves this by linking to required open notice requirements. Mandatory links, proportional to the context of consent, must be recorded in the receipt so that it can be contextually relevant and scale to the widest array of contexts.   (I.e. icons, trust frameworks, identity frameworks, reputation frameworks)

The MVCR is intended to be measurable as a basis for consent frameworks by, being a versatile consent receipt, that is scalable for market and cross domain self-regulation of consent. (?)

All components of the receipt are then usable, in any order post consent, to create iterative updates to the consent. Maintaining a current 'state' of consent authorisation policy across contexts. 
(note: should the MVCR - refer to a record, and the iterative updates referred to as receipts? 
(note: proportionality needs to be defined)

**Comment by PrivacyCDN** [comment]
In my view the MVCR - i.e. the version that we are trying to get done is an
artefact to hold a minimum set of data - which this working group believes
to be sufficient to be able to convey the minimum amount of information
necessary to record a personal information transaction.

This entire ## Legal Policy ## section can/should be moved out of the MVCR
spec - where we will fight over it - and put in the parking lot or in the
explanatory part of the wiki.

Sincerely,
John Wunderlich
@PrivacyCDN

Call: +1 (647) 669-4749
eMail: john@wunderlich.ca

On 29 February 2016 at 13:55, Mark Lizar notifications@github.com wrote:

> ##Legal Policy
> The receipt is a legal policy document in so much that is designed to be a
> host to consent notice requirements and be used to certify trust based
> frameworks.
> 
> It achieves this by linking to required open notice requirements.
> Mandatory links, proportional to the context of consent, must be recorded
> in the receipt so that it can be contextually relevant and scale to the
> widest array of contexts. (I.e. icons, trust frameworks, identity
> frameworks, reputation frameworks)
> 
> The MVCR is intended to be measurable as a basis for consent frameworks
> by, being a versatile consent receipt, that is scalable for market and
> cross domain self-regulation of consent. (?)
> 
> All components of the receipt are then usable, in any order post consent,
> to create iterative updates to the consent. Maintaining a current 'state'
> of consent authorisation policy across contexts.
> (note: should the MVCR - refer to a record, and the iterative updates
> referred to as receipts?
> (note: proportionality needs to be defined)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/KantaraInitiative/CISWG/issues/19.

## 

This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. If you are not the intended recipient 
you are notified that disclosing, copying, distributing or taking any 
action in reliance on the contents of this information is strictly 
prohibited.

**Comment by smartopian** [comment]
+1 

I have moved this intro into issues #17, 18 and 19.  Leaving just the index and the sections to go through. 

It was meant to show what was meant by legal inter-operability -  The entire section at this point is a  straw man to illustrate how what goes in the tables is directed by what we mean by validation and compliance in the spec.  

So I had removed it from the home page and just left the index.
- Mark

**Comment by PrivacyCDN** [comment]
Thx

Sincerely,
John Wunderlich
@PrivacyCDN

Call: +1 (647) 669-4749
eMail: john@wunderlich.ca

On 29 February 2016 at 14:54, Mark Lizar notifications@github.com wrote:

> +1
> 
> I have moved this intro into issues #17, 18 and 19. Leaving just the index
> and the sections to go through.
> 
> It was meant to show what was meant by legal inter-operability - The
> entire section at this point is a straw man to illustrate how what goes in
> the tables is directed by what we mean by validation and compliance in the
> spec.
> 
> So I had removed it from the home page and just left the index.
> - Mark
> 
> > On 29 Feb 2016, at 19:47, John Wunderlich notifications@github.com
> > wrote:
> > 
> > In my view the MVCR - i.e. the version that we are trying to get done is
> > an
> > artefact to hold a minimum set of data - which this working group
> > believes
> > to be sufficient to be able to convey the minimum amount of information
> > necessary to record a personal information transaction.
> > 
> > This entire ## Legal Policy ## section can/should be moved out of the
> > MVCR
> > spec - where we will fight over it - and put in the parking lot or in the
> > explanatory part of the wiki.
> > 
> > Sincerely,
> > John Wunderlich
> > @PrivacyCDN
> > 
> > Call: +1 (647) 669-4749
> > eMail: john@wunderlich.ca
> > 
> > On 29 February 2016 at 13:55, Mark Lizar notifications@github.com
> > wrote:
> > 
> > > ##Legal Policy
> > > The receipt is a legal policy document in so much that is designed to
> > > be a
> > > host to consent notice requirements and be used to certify trust based
> > > frameworks.
> > > 
> > > It achieves this by linking to required open notice requirements.
> > > Mandatory links, proportional to the context of consent, must be
> > > recorded
> > > in the receipt so that it can be contextually relevant and scale to the
> > > widest array of contexts. (I.e. icons, trust frameworks, identity
> > > frameworks, reputation frameworks)
> > > 
> > > The MVCR is intended to be measurable as a basis for consent frameworks
> > > by, being a versatile consent receipt, that is scalable for market and
> > > cross domain self-regulation of consent. (?)
> > > 
> > > All components of the receipt are then usable, in any order post
> > > consent,
> > > to create iterative updates to the consent. Maintaining a current
> > > 'state'
> > > of consent authorisation policy across contexts.
> > > (note: should the MVCR - refer to a record, and the iterative updates
> > > referred to as receipts?
> > > (note: proportionality needs to be defined)
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/KantaraInitiative/CISWG/issues/19.
> > 
> > ## 
> > 
> > This email and any files transmitted with it are confidential and
> > intended
> > solely for the use of the individual or entity to whom they are
> > addressed.
> > If you have received this email in error please notify the system
> > manager.
> > This message contains confidential information and is intended only for
> > the
> > individual named. If you are not the named addressee you should not
> > disseminate, distribute or copy this e-mail. Please notify the sender
> > immediately by e-mail if you have received this e-mail by mistake and
> > delete this e-mail from your system. If you are not the intended
> > recipient
> > you are notified that disclosing, copying, distributing or taking any
> > action in reliance on the contents of this information is strictly
> > prohibited.
> > —
> > Reply to this email directly or view it on GitHub <
> > https://github.com/KantaraInitiative/CISWG/issues/19#issuecomment-190352588
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/KantaraInitiative/CISWG/issues/19#issuecomment-190354850
> .

## 

This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. If you are not the intended recipient 
you are notified that disclosing, copying, distributing or taking any 
action in reliance on the contents of this information is strictly 
prohibited.

**Comment by smartopian** [comment]
addressed
