### ISSUE TITLE
Removing subject ID field from the Consent Receipt & Specifify Receipt Data Payload to be in the receipt provisioned 

### ISSUE THREAD

**Issue by smartopian** [KantaraInitiative/CISWG#23]
This issue is a suggestion to remove the subject id field from the consent receipt field so that the consent receipt fields don't contain PII, but, instead, attached is the receipt payload with all of the data entered by the consent grantee.
The benefit would be that the receipt fields themselves don't contain PII, thus are less sensitive themselves, with the PII entered into  the receipt delivered in the receipt payload.

The payload of PII data would t be provisioned to the consent grantee, but not displayed on the website, via the consent receipt as to protect privacy and be privacy by design.

**Comment by smartopian** [comment]
The subject ID has been changed to Principle ID - in accordance with ISO terminology and kept in the MVCR.  (as subject identity is required for consent)

**Comment by iainh1** [comment]
I was showing consent receipt spec as is to some newbies today. Many of the terms led them to say ‘what do you mean by that?’

We may need another column for a genuinely end user friendly labels.
