### ISSUE TITLE
GDPR Review

### ISSUE THREAD

**Issue by smartopian** [KantaraInitiative/CISWG#25]
Criteria to review the  MVCR against EUGDPR criteria

**Comment by smartopian** [comment]
There are a lot of items and technical points for consent in the GDPR, I recommend a workshop or report on these items this summer and a review of the specification for the GDPR.

**Comment by PrivacyCDN** [comment]
Recommending closing this issue. After v 1 is out the door we can consider a more general consideratino of the relationship between the v 2 receipt and various privacy regimes - possibly starting with the GDPR as a high water mark standard. This isn't an issue for v 1
