### ISSUE TITLE
PI Subject field : what is its purpose? should it be seperated from the person who gives consent? 

### ISSUE THREAD

**Issue by smartopian** [KantaraInitiative/CISWG#28]
The PI subject is a nice field, although there is no clearly agreed purpose 

(this is as its stated at the moment)
| PI Subject | An identifier or token for the natural person whose information has been collected and who has given consent | Required | John Doe |

First of all, requiring  a PI identifier provides a privacy risk as it makes the consent receipt and the person who gave the consent a direct link in the receipt record.   Although, this could be mitigated by requiring the receipt is hashed, ie. reciept is stored as JWT .    

Second, the person whose information is collected is not always the person providing consent, their are circumstances, where the consent decision/provision is delegated to  a parent/guardian/care-taker/emergency scenario.  This brings up the questions if not only a subject identifier is required (so that the person who holds the receipt can prove it is their ( a single layer of authentication) but, if the identity of a delegate for consent is required for compliance.  As a result, an action item for post V0.8 draft @KantaraInitiative/ciswg  is to discuss if another field for delegate (like the delegation for Data Controller) should be added to the specification below PI subject.

**Comment by PrivacyCDN** [comment]
The purpose is to identify the person for whose information the consent applies. Seems self evident from the name PI Subject.
The receipt is a record of a transaction between two parties, both of whom are identified in the record.
The point about delegation is valid but not, I think, part of the 'minimum' receipt, which is based on the Alice and Bob scenario where they are representing themselves.

**Comment by smartopian** [comment]
> On 27 Mar 2016, at 02:30, John Wunderlich notifications@github.com wrote:
> 
> The purpose is to identify the person for whose information the consent applies. Seems self evident from the name PI Subject.
> 
> After some thought, the data submitted by the individual can be used to identify the individual to the Grantor,  so that this identifier is not required by the grantee to be in the receipt, but, as per the scope of the Minimum viable consent receipt being usable by the grantee to prove that they are the ones the provided the consent in the first place, this identifier is a requirement so that it provides an initial identifier that can be used to  corroberate a grantee claim of provisioning consent. 
> The receipt is a record of a transaction between two parties, both of whom are identified in the record.
> 
> This makes sense, again so that the consent receipt can be minimum viable as a stand alone consent record. (again speaks to scope)

Both points of Subject Identifier - purpose that facilities the use of the MVCR as a viable stand alone record. (with no objections to this purpose this part of the issue can be closed) 

> The point about delegation is valid but not, I think, part of the 'minimum' receipt, which is based on the Alice and Bob scenario where they are representing themselves

The scope of the minimum receipt has never been defined as a single consent context between two parties.  The two party use case was brought up and suggested to be exclusive, but, it was clear that all use cases for the mvcr should be considered. 

As Editor: I  recommend that we add this as an action @KantaraInitiative/CISWG item and  table this item post the v0.8 draft.  With the recommendation that the WG consider adding an additional field under PI Subject, that a subfield, _ on behalf_ of Pi Subject be created, following the same pattern as the data controller field. So as to have delegation for both the PI controller and the PI subject. 
(this should be made into its own issue)

**Comment by smartopian** [comment]
addressed already in issue #23
