### ISSUE TITLE
Adding Grantee & Grantor terms: Mapping them to existing spec terms

### ISSUE THREAD

**Issue by smartopian** [KantaraInitiative/CISWG#29]
I have noticed that lots of the language in the specification is a bit awkward in that we have been trying to use the ISO 29100 terminology framework of a consent centric specification.  Even though the ISO privacy framework is a very helpful base for terms and concepts it is not consent centric and really available as terms people can grasp and use. 

In this regard, I have been playing with the terms Grantee and Grantor as operational terms to describe Alice and Bob’s role in the consent . 

Grantee - being the entity provisioning (or giving) consent - Grantor being the entity that is harvesting the consent ( or taking)  consent. I like grantee, as it embodies a person and has an inherent rights to manage the use of consent post provision. 

Would there being objection to adding these two terms to the spec and mapping:
1. grantee to PI subject, Data subject,
2. grantor to PI Controller, Data Controller

**Comment by PrivacyCDN** [comment]
Grantor and Grantee are new terms which, to my knowledge are not used by
data protection authorities or in extant privacy policy. We have been
removing items from the MVCR to simplify it and move to v 1.0 as quickly as
possible. My vote is to be put these terms on the roadmap for post MVCR​,
and not use them now.

Sincerely,
John Wunderlich
@PrivacyCDN

Call: +1 (647) 669-4749
eMail: john@wunderlich.ca

On 27 March 2016 at 14:18, Mark Lizar notifications@github.com wrote:

> I have noticed that lots of the language in the specification is a bit
> awkward in that we have been trying to use the ISO 29100 terminology
> framework of a consent centric specification. Even though the ISO privacy
> framework is a very helpful base for terms and concepts it is not consent
> centric and really available as terms people can grasp and use.
> 
> In this regard, I have been playing with the terms Grantee and Grantor as
> operational terms to describe Alice and Bob’s role in the consent .
> 
> Grantee - being the entity provisioning (or giving) consent - Grantor
> being the entity that is harvesting the consent ( or taking) consent. I
> like grantee, as it embodies a person and has an inherent rights to manage
> the use of consent post provision.
> 
> Would there being objection to adding these two terms to the spec and
> mapping:
> 1. grantee to PI subject, Data subject,
> 2. grantor to PI Controller, Data Controller
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/KantaraInitiative/CISWG/issues/29

## 

This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. If you are not the intended recipient 
you are notified that disclosing, copying, distributing or taking any 
action in reliance on the contents of this information is strictly 
prohibited.

**Comment by smartopian** [comment]
We have been removing fields from the MVCR to move to a minimum viable, but, we have not been removing things from the spec so that we can move as quickly as possible.  

Nor is their a requirement to use terms that regulators or lawyer use in policy. 

(just saying)

**Comment by PrivacyCDN** [comment]
It seems to me that one significant purpose for a consent receipt is to
have an artefact that parties can point to in the event of a dispute. And
who is the likely recipient of a complaint re: an abuse of consent? That
would be a data protection authority. And who would be managing the consent
inside the organization that is emitting them - privacy professionals and
lawyers. So while it’s not a requirement that we use terms that privacy
professionals and data protection authorities are familiar with, it seems a
practical plus to do so where possible for ease of adoption and
evangelizing in the community.

Sincerely,
John Wunderlich
@PrivacyCDN

Call: +1 (647) 669-4749
eMail: john@wunderlich.ca

On 27 March 2016 at 18:13, Mark Lizar notifications@github.com wrote:

> We have been removing fields from the MVCR to move to a minimum viable,
> but, we have not been removing things from the spec so that we can move as
> quickly as possible.
> 
> Nor is their a requirement to use terms that regulators or lawyer use in
> policy.
> 
> (just saying)
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/KantaraInitiative/CISWG/issues/29#issuecomment-202031876

## 

This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. If you are not the intended recipient 
you are notified that disclosing, copying, distributing or taking any 
action in reliance on the contents of this information is strictly 
prohibited.

**Comment by smartopian** [comment]
I Don’t disagree, but, I would think the most significant - is the user. , making the consent receipt operationally and independently usable for the consentee being a high priority.

**Comment by smartopian** [comment]
issues is addressed, no terms unless referenced to legal references or IS029100 or similar
