### ISSUE TITLE
PI Categories: What are these ?  

### ISSUE THREAD

**Issue by smartopian** [KantaraInitiative/CISWG#31]
In the latest version of the spec there is a field for PII categories, which,, requires a list of PII categories. 
- is there a list?  should a list be appended to the spec, referred to externally, defined or free text. 

Similar issues pertains to selecting purpose categories and for consent types.

**Comment by PrivacyCDN** [comment]
​To my knowledge there is no agreed upon list of categories, and this
varies from jurisdiction to jurisdiction. This is another case where I
should think we could provide a list, but allow additions to the list when
deployed.​

Sincerely,
John Wunderlich
@PrivacyCDN

Call: +1 (647) 669-4749
eMail: john@wunderlich.ca

On 29 March 2016 at 00:50, Mark Lizar notifications@github.com wrote:

> In the latest version of the spec there is a field for PII categories,
> which,, requires a list of PII categories.
> - is there a list? should a list be appended to the spec, referred to
>   externally, defined or free text.
> 
> Similar issues pertains to selecting purpose categories and for consent
> types.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/KantaraInitiative/CISWG/issues/31

## 

This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. If you are not the intended recipient 
you are notified that disclosing, copying, distributing or taking any 
action in reliance on the contents of this information is strictly 
prohibited.

**Comment by smartopian** [comment]
I think for sensitive data this is very clear.  Perhaps common purposes as well, but,  am not convinced these lists should be in the scope of the MVCR specification. and if they are, they would need to be defined and maintained by the WG on an ongoing basis. Which is also not a scope the WG has at the moment. 

For example, the current list of purposes, I would not recommend that the WG endorse as they are not defined for a consent record context. this is also a lot of work. 

So I recommend an action to define list post v0.8 draft.

**Comment by smartopian** [comment]
Purpose Specification list is now tabled to the summer conversation and should be on the Agenda for discussion or tabled to V2. in September

**Comment by iainh1** [comment]
Not sure this is really a viable option in that we need to have at least a base list of purposes for v 1?

Iain

**Comment by smartopian** [comment]
The thinking here is that we would be looking towards specifying how to provide a purpose specification list, not decide what the purpose specifications are, and until then, use and ratify the existing list we have in the Appendix.  In July the EU DP Commissioners are meeting with Trade Associations to discuss harmonisation of terminology and the like.

**Comment by PrivacyCDN** [comment]
Folks;

I agree that providing a non-exclusive list of potential purposes for an
issuer to put in their consent receipt will be both helpful and useful, so
long as the issuer of the receipt can add or modify to the list to match
their particular customer and regulatory requirements.

There is an underlying important point to be made here - that the consent
receipt cannot and should not be seen, in and of itself, as a guarantee of
compliance with any particular data protection regime or regulation. This
is equally true of a cash receipt. It doesn’t guarantee that the retailer
is in compliance with accounting or any other retail compliance regime.

Thus we can not be prescriptive as to the purposes that are actually
included on the receipt. The issuer is accountable for making that
determination and to ensuring that they are, in fact, in compliance with
whatever data protection regime they are operating under.

JW

Sincerely,
John Wunderlich
@PrivacyCDN

Call: +1 (647) 669-4749
eMail: john@wunderlich.ca

On 14 May 2016 at 04:27, Mark Lizar notifications@github.com wrote:

> The thinking here is that we would be looking towards specifying how to
> provide a purpose specification list, not decide what the purpose
> specifications are, and until then, use and ratify the existing list we
> have in the Appendix. In July the EU DP Commissioners are meeting with
> Trade Associations to discuss harmonisation of terminology and the like.
> 
> > On 12 May 2016, at 22:26, iainh1 notifications@github.com wrote:
> > 
> > Not sure this is really a viable option in that we need to have at least
> > a base list of purposes for v 1?
> > 
> > Iain
> > 
> > > On 12 May 2016, at 12:56, Mark Lizar notifications@github.com wrote:
> > > 
> > > Purpose Specification list is now tabled to the summer conversation
> > > and should be on the Agenda for discussion or tabled to V2. in September
> > > 
> > > —
> > > You are receiving this because you are subscribed to this thread.
> > > Reply to this email directly or view it on GitHub <
> > > https://github.com/KantaraInitiative/CISWG/issues/31#issuecomment-218735893
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub <
> > https://github.com/KantaraInitiative/CISWG/issues/31#issuecomment-218890928
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/KantaraInitiative/CISWG/issues/31#issuecomment-219208102

## 

This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. If you are not the intended recipient 
you are notified that disclosing, copying, distributing or taking any 
action in reliance on the contents of this information is strictly 
prohibited.

**Comment by maryhodder** [comment]
1. PII Categories? Should this be a MUST in the Field table?

AGREEMENT: Yes, keep as MUST, but our suggested list to implementers will appear in Appendix and we will elaborate on use of these in the Supplemental Guidance.

Agreed on last thursday's call.
