### ISSUE TITLE
MVCR ISSUE: Express and Explicit Consent : Valid & Informed Consent  : Withdraw Consent 

### ISSUE THREAD

**Issue by smartopian** [KantaraInitiative/CISWG#33]
For the MVCR there is a history of the term express and explicit in the EU.  Section 5.4.4 

Found here: 
https://goo.gl/JGPX2Y (the history of consent regulation in the EU. ) 

Which ended up with explicit being put into regulation.  

As well, there is a history of Informed Consent, which goes back to 1964 Declaration of Helsinki and the requirement for being able to withdraw consent. 

This can be found in section 2.3.3

(same doc) https://goo.gl/JGPX2Y

**Comment by smartopian** [comment]
@dturnerx did you get a chance to read this ?

(same doc) https://goo.gl/JGPX2Y. -  its the best history on consent I have ever come across..

**Comment by dturnerx** [comment]
I'll have a look. Thanks.
