### ISSUE TITLE
Columns for specificy of fields: (includes Data Types) 

### ISSUE THREAD

**Issue by smartopian** [KantaraInitiative/CISWG#34]
Here are the updated columns: 

Receipt Field Label,    Receipt Field Format,   Data Field Name,    Data Type,  Example Data Input,     Receipt Field Description,  Purpose of Field,   Linked,

They include data field name type, so as to be machine readable, but this is not a requirement for the Minimum MVCR.   I have also moved the link  requirement from Collection Site , to a column field, this can be used to reference a field any with an external link to an icon or required information.   also, removes the need for the Collection Site field in the MVCR.

**Comment by PrivacyCDN** [comment]
Recommend closing
