### ISSUE TITLE
Change Name of MVCR Profile to 'Networked Consent Receipt'

### ISSUE THREAD

**Issue by smartopian** [KantaraInitiative/CISWG#37]
It is quite easy to define fields like Jurisdiction as a MUST for networked consent receipts.  
Need to take a deeper look, but this could be what we advertise as the spec output?  Thoughts?

**Comment by PrivacyCDN** [comment]
Big no on the name change. We’ve done a lot of work around MVCR.

Networked consent receipt sounds like post Minimum work

Sincerely,
John Wunderlich
@PrivacyCDN

Call: +1 (647) 669-4749
eMail: john@wunderlich.ca

On 10 April 2016 at 06:51, Mark Lizar notifications@github.com wrote:

> It is quite easy to define fields like Jurisdiction as a MUST for
> networked consent receipts.
> 
> Need to take a deeper look, but this could be what we advertise as the
> spec output? Thoughts?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/KantaraInitiative/CISWG/issues/37

## 

This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. If you are not the intended recipient 
you are notified that disclosing, copying, distributing or taking any 
action in reliance on the contents of this information is strictly 
prohibited.

**Comment by smartopian** [comment]
i was referring to naming/defining the standard consent receipt profile -- AKA - the Alice  & Bob - standard online website MVCR profile. (not the name of the specification).    - I agree with the " lets just make it the one thing for now" vibe ->  i.e.   MVCR - its the basic Alice & Bob website/IOT consent record and receipt information .   - what do you think of something like - The MVCR  is designed to limit liability to be easily used by orgs to  open consent so people can  see and communicate about a consent if they want, while org's can be more compliant and marketing more innovative? (big disclaimer - not for sensitive personal data categories or compliance certified receipts until post  v1 )

**Comment by smartopian** [comment]
What about  Basic MVCR or MVCR Lite for v.1

**Comment by PrivacyCDN** [comment]
This is a distraction. I thought that we were agree that we would focus on
agreeing on the fields/information for the MVCR so that we could then move
on to the other issues on the roadmap. Can we just focus on that - a single
set of agreed upon information that constitutes the minimum necessary
information for the general purposes of a consent receipt?

Sincerely,
John Wunderlich
@PrivacyCDN

Call: +1 (647) 669-4749
eMail: john@wunderlich.ca

On 14 April 2016 at 02:29, Mark Lizar notifications@github.com wrote:

> What about Basic MVCR or MVCR Lite for v.1
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/KantaraInitiative/CISWG/issues/37#issuecomment-209582831

## 

This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. If you are not the intended recipient 
you are notified that disclosing, copying, distributing or taking any 
action in reliance on the contents of this information is strictly 
prohibited.

**Comment by smartopian** [comment]
this is concentrating on the single v1 MVCR  - which is what I am working on specifying and why I bring it up -->  the  v1 MVCR - has the basic MVCR profile the rest is moved to the appendix.  (so I think we are talking about the same thing)  The Basic MVCR - is the V1, Sensitive Data Categories and complaince  (with laws and ISO) in V2.  
Basic is good

**Comment by PrivacyCDN** [comment]
In my head it looks like this:

V1 - Minimum Viable Consent Receipt (standard that defines the necessary
information)

V2 - Consent Receipt (specification including multiple scenarios, profiles
and code)

Sincerely,
John Wunderlich
@PrivacyCDN

Call: +1 (647) 669-4749
eMail: john@wunderlich.ca

On 14 April 2016 at 08:09, Mark Lizar notifications@github.com wrote:

> this is the name v1MVCR profile, the idea being that the rest is moved to
> the appendix. (so I think we are talking about the same thing) The idea
> here is that Basic is MVCR V1, Sensitive Data Categories and complaince
> (with laws and ISO) in V2.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/KantaraInitiative/CISWG/issues/37#issuecomment-209697127

## 

This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. If you are not the intended recipient 
you are notified that disclosing, copying, distributing or taking any 
action in reliance on the contents of this information is strictly 
prohibited.

**Comment by smartopian** [comment]
I think we are pretty close then. 

v1 - normative baseline profile: MVCR (online) - to provide open consent receipts for consent and information sharing.  (what do you think?)   - 

v2, (appendix A)  a) explicit consent and sensitive information sharing mapped to ISO 29100 , machine readable, b)  used for legal compliance - (creating legal profiles) 
(its important for other stakeholders and the spec that people know that the v.2 is building on V.1 and taking the standards and legal requirements seriously. 

I am just trying to sanitise it and clean it up,  work on the guidance in google docs.  now.

**Comment by iainh1** [comment]
I understand the point being made here, but think we need to move beyond MVCR as a term. It is confusing us intra-group, and has no meaning whatsoever to real customers of the spec.
Taking John's focus of 'a single set of agreed upon information that constitutes the minimum necessary information for the general purposes of a consent receipt" as the target, then I think we are almost there. I propose the name Consent Receipt v 1 as one that says what it is and can be meaningful to the customer.

ALL stuff in the spec that is not about that should go to the appendices.

**Comment by PrivacyCDN** [comment]
Sounds about right. If we take that approach, once we agree on the fields,
then hopefully we can go back to Justin and/or Sarah to update the JSON and
include that in the appendices as an example of a digital consent receipt.

Sincerely,
John Wunderlich
@PrivacyCDN

Call: +1 (647) 669-4749
eMail: john@wunderlich.ca

On 3 May 2016 at 12:30, iainh1 notifications@github.com wrote:

> I understand the point being made here, but think we need to move beyond
> MVCR as a term. It is confusing us intra-group, and has no meaning
> whatsoever to real customers of the spec.
> Taking John's focus of 'a single set of agreed upon information that
> constitutes the minimum necessary information for the general purposes of a
> consent receipt" as the target, then I think we are almost there. I propose
> the name Consent Receipt v 1 as one that says what it is and can be
> meaningful to the customer.
> 
> ALL stuff in the spec that is not about that should go to the appendices.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/KantaraInitiative/CISWG/issues/37#issuecomment-216585879

## 

This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. If you are not the intended recipient 
you are notified that disclosing, copying, distributing or taking any 
action in reliance on the contents of this information is strictly 
prohibited.

**Comment by iainh1** [comment]
I will send a version of the receipt later this week that is delivered from Salesforce. That strips out all of the baggage around it, and shows a simple set of fields in a specific order, with useful descriptions and deliverables easily at large scale.  (And indeed loggable on the Stellar Blockchain via JLINC.

Iain

**Comment by PrivacyCDN** [comment]
Looking forward to seeing it. 

Get Outlook for iOS

On Tue, May 3, 2016 at 10:43 AM -0700, "iainh1" notifications@github.com wrote:

I will send a version of the receipt later this week that is delivered from Salesforce. That strips out all of the baggage around it, and shows a simple set of fields in a specific order, with useful descriptions and deliverables easily at large scale.  (And indeed loggable on the Stellar Blockchain via JLINC.

Iain

> On 3 May 2016, at 18:20, John Wunderlich notifications@github.com wrote:
> 
> Sounds about right. If we take that approach, once we agree on the fields,
> 
> then hopefully we can go back to Justin and/or Sarah to update the JSON and
> 
> include that in the appendices as an example of a digital consent receipt.
> 
> Sincerely,
> 
> John Wunderlich
> 
> @PrivacyCDN
> 
> Call: +1 (647) 669-4749
> 
> eMail: john@wunderlich.ca
> 
> On 3 May 2016 at 12:30, iainh1 notifications@github.com wrote:
> 
> > I understand the point being made here, but think we need to move beyond
> > 
> > MVCR as a term. It is confusing us intra-group, and has no meaning
> > 
> > whatsoever to real customers of the spec.
> > 
> > Taking John's focus of 'a single set of agreed upon information that
> > 
> > constitutes the minimum necessary information for the general purposes of a
> > 
> > consent receipt" as the target, then I think we are almost there. I propose
> > 
> > the name Consent Receipt v 1 as one that says what it is and can be
> > 
> > meaningful to the customer.
> > 
> > ALL stuff in the spec that is not about that should go to the appendices.
> > 
> > —
> > 
> > You are receiving this because you were mentioned.
> > 
> > Reply to this email directly or view it on GitHub
> > 
> > https://github.com/KantaraInitiative/CISWG/issues/37#issuecomment-216585879
> 
> ## 
> 
> This email and any files transmitted with it are confidential and intended 
> 
> solely for the use of the individual or entity to whom they are addressed. 
> 
> If you have received this email in error please notify the system manager. 
> 
> This message contains confidential information and is intended only for the 
> 
> individual named. If you are not the named addressee you should not 
> 
> disseminate, distribute or copy this e-mail. Please notify the sender 
> 
> immediately by e-mail if you have received this e-mail by mistake and 
> 
> delete this e-mail from your system. If you are not the intended recipient 
> 
> you are notified that disclosing, copying, distributing or taking any 
> 
> action in reliance on the contents of this information is strictly 
> 
> prohibited.
> 
> —
> 
> You are receiving this because you commented.
> 
> Reply to this email directly or view it on GitHub

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub

## 

This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. If you are not the intended recipient 
you are notified that disclosing, copying, distributing or taking any 
action in reliance on the contents of this information is strictly 
prohibited.

**Comment by smartopian** [comment]
Name changed from MVCR to COnsent Receipt And agreed on call May 2nd
