### ISSUE TITLE
MVCR: Guidance & Example 

### ISSUE THREAD

**Issue by smartopian** [KantaraInitiative/CISWG#39]
I have started a new table for field, description Confomance, and Guidance to go with the examples in the spec. 
its the tab called guidance. 
https://docs.google.com/spreadsheets/d/1KmHxYJRNxtDZsy5hSDTHcQTZbsxI-cMQ7HE7hd47DUU/edit?usp=sharing

if you want to take a look at this table and discuss or comment on it, this might be fastest way for us to get this into shape collaboratively.   - I am going to work on the guidance  in the spreadsheet, and work on the rest on getting the rest of the spec cleaned up.

**Comment by iainh1** [comment]
We need to be working in a sheet with fields in the proposed receipt v 1 order, and then work through Field Name, Field Description, Field Type and Field Guidance to optimise all of those. My revview/ build in Salesforce showed that none of these are currently as they need to be.

**Comment by smartopian** [comment]
Thanks Iain, 

We are using the fields and order you suggest.  If you want to change them or suggest others right away so we can include this in the v0.8 edit — so please  go ahead. 

 Or, we can post to the group for more comments.   Either way,   it is that the data type and data field names need to be static in the specification so that the spec has a common machine readable component, but the english label of the field and the order is ultimately up to the implementor. 

I suggest we add back in the JSON example into the table as well, and then move forward with what you have already provided.   I doubt that we will have time before v0.8 to discuss and go through these again. 

Although, from v0.8 to v0.9 the plan is to definitely improve on guidance and presentation .  do you want  post the spreadsheet to the mailing list?  ask for comment?  then take these fields and put them in the spec / with guidance and example of the Kantara Implementation?

**Comment by iainh1** [comment]
OK, here is my list of the 18 fields I think should be in v 1.

In my view, most of the names and descriptions could be included if we tried.

I don’t have guidance in this one, do you want to add?

If anyone else wants to chip with comments to suggestions prior to tonight’s call then please respond to this email with them and i’ll collate prior to the call.

Cheers

Iain

**Comment by smartopian** [comment]
HI Iain, 

these fields didn’t come through in email, but, I assume that these are 18 fields we have already?  Are these the fields you think should be must? 

or are you suggesting that we remove fields from the v.1?  Either way, please post these to the list with the guidance we have so far so we can collaborate, or if you like, in google docs, to make collaboration easy enough for people to comment.   

This would be a great help.

**Comment by iainh1** [comment]
I'm out at present, will do that mid afternoon

**Comment by iainh1** [comment]
Here is a version of the spreadsheet with guidance copied over from the Google sheet.

Any comments, amends or builds, please circulate before the call tonight at 9 UK time.

Cheers

Iain

**Comment by PrivacyCDN** [comment]
No attachments or link in my email

On Monday, 23 May 2016, iainh1 notifications@github.com wrote:

> Here is a version of the spreadsheet with guidance copied over from the
> Google sheet.
> 
> Any comments, amends or builds, please circulate before the call tonight
> at 9 UK time.
> 
> Cheers
> 
> Iain
> 
> > On 23 May 2016, at 11:04, Mark Lizar <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> > 
> > HI Iain,
> > 
> > these fields didn’t come through in email, but, I assume that these are
> > 18 fields we have already? Are these the fields you think should be must?
> > 
> > or are you suggesting that we remove fields from the v.1? Either way,
> > please post these to the list with the guidance we have so far so we can
> > collaborate, or if you like, in google docs, to make collaboration easy
> > enough for people to comment.
> > 
> > This would be a great help.
> > 
> > > On 23 May 2016, at 10:37, iainh1 <notifications@github.com
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> > > 
> > > OK, here is my list of the 18 fields I think should be in v 1.
> > > 
> > > In my view, most of the names and descriptions could be included if we
> > > tried.
> > > 
> > > I don’t have guidance in this one, do you want to add?
> > > 
> > > If anyone else wants to chip with comments to suggestions prior to
> > > tonight’s call then please respond to this email with them and i’ll collate
> > > prior to the call.
> > > 
> > > Cheers
> > > 
> > > Iain
> > > 
> > > > On 23 May 2016, at 10:31, Mark Lizar <notifications@github.com
> > > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> > > > 
> > > > Thanks Iain,
> > > > 
> > > > We are using the fields and order you suggest. If you want to change
> > > > them or suggest others right away so we can include this in the v0.8 edit —
> > > > so please go ahead.
> > > > 
> > > > Or, we can post to the group for more comments. Either way, it is
> > > > that the data type and data field names need to be static in the
> > > > specification so that the spec has a common machine readable component, but
> > > > the english label of the field and the order is ultimately up to the
> > > > implementor.
> > > > 
> > > > I suggest we add back in the JSON example into the table as well,
> > > > and then move forward with what you have already provided. I doubt that we
> > > > will have time before v0.8 to discuss and go through these again.
> > > > 
> > > > Although, from v0.8 to v0.9 the plan is to definitely improve on
> > > > guidance and presentation . do you want post the spreadsheet to the mailing
> > > > list? ask for comment? then take these fields and put them in the spec /
> > > > with guidance and example of the Kantara Implementation?
> > > > 
> > > > > On 23 May 2016, at 09:55, iainh1 <notifications@github.com
> > > > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> > > > > 
> > > > > We need to be working in a sheet with fields in the proposed
> > > > > receipt v 1 order, and then work through Field Name, Field Description,
> > > > > Field Type and Field Guidance to optimise all of those. My revview/ build
> > > > > in Salesforce showed that none of these are currently as they need to be.
> > > > > 
> > > > > —
> > > > > You are receiving this because you authored the thread.
> > > > > Reply to this email directly or view it on GitHub <
> > > > > https://github.com/KantaraInitiative/CISWG/issues/39#issuecomment-220923742
> > > > 
> > > > —
> > > > You are receiving this because you commented.
> > > > Reply to this email directly or view it on GitHub <
> > > > https://github.com/KantaraInitiative/CISWG/issues/39#issuecomment-220931881
> > > 
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly or view it on GitHub <
> > > https://github.com/KantaraInitiative/CISWG/issues/39#issuecomment-220933190
> > 
> > —
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub <
> > https://github.com/KantaraInitiative/CISWG/issues/39#issuecomment-220938993
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/KantaraInitiative/CISWG/issues/39#issuecomment-221009381

## 

John Wunderlich

Fat fingered from a mobile device
Pleez 4give spelling errurz!

## 

This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. If you are not the intended recipient 
you are notified that disclosing, copying, distributing or taking any 
action in reliance on the contents of this information is strictly 
prohibited.

**Comment by iainh1** [comment]
Strange, that’s twice, and I definitely attached. Must be getting stripped out somewhere.

I’ve reposted in Google sheet as below.

https://docs.google.com/spreadsheets/d/1ooq5UnBivt2CVDEGMuSXypozVizwvIhhsRtz8-fnj_A/edit?usp=sharing https://docs.google.com/spreadsheets/d/1ooq5UnBivt2CVDEGMuSXypozVizwvIhhsRtz8-fnj_A/edit?usp=sharing

My own take is the field list, order and logic is fine; the precise terms and how we explain them could all be improved on. That was the feedback from my Salesforce team who tried to implement, i.e. they could see the logic but precise terminology was not really clear to those not close to the spec. Those not close are who we need to build for.

Cheers

Iain

**Comment by smartopian** [comment]
So, no secondary purpose?

**Comment by smartopian** [comment]
also, I think we need to keep scope in as optional, or else consent tokens and UMA, IDSEG, and MYdata project will not find this useful.

**Comment by smartopian** [comment]
are you also suggesting that these are the only columns in the v.08 spec?

**Comment by smartopian** [comment]
Is the logic and order addressed in another issue, or should this issue be renamed/re-created as a current issue?  - recommend closing and opening a new specific issue here if needed.

**Comment by maryhodder** [comment]
We can take a look at this list of 18, in the order Iain proposes, during
the field table review.
