### ISSUE TITLE
Listing Purposes for  PI or PII : If PI there are a lot more purposes to list

### ISSUE THREAD

**Issue by smartopian** [KantaraInitiative/CISWG#40]
in the receipt listing categories of personal data

If the receipt is for PI  then does this mean the org needs t account for shairing of 
- IP Address - logs
- Session Cookies - confluence and wiki 
- Google Analytics  - these would all be listed implied purposes listed on the receipt? 

If for PII
- then is it just  for categories for personal data?

**Comment by iainh1** [comment]
At this stage, if we want to get something out the door, it can only be categories, so the trick lies in having an excellent list of categories.

**Comment by smartopian** [comment]
Purpose Categories and PI Categories are required.  THe suggestion in the past is to provide a list for the time being, but have other - as a categories so categories can be created by implementors.  In the EU , the catagories of purpose also need to be harmonised across 28 countries and quite a few languages, so, this will most likely be a topic that will go on for a while and perhaps be addressed by ISO.

**Comment by PrivacyCDN** [comment]
See my comments in the copy of Iain's google document that I posted.
Purpose categories are metadata about purposes. It seems to me that the
critical piece is ensuring that purposes are listed. The question of
harmonizing across the EU is a compliance issue not a spec/standard issue.
It will be up to the entity issuing the consent to ensure that they have
those ducks lined up.

Sincerely,
John Wunderlich
@PrivacyCDN

Call: +1 (647) 669-4749
eMail: john@wunderlich.ca

On 23 May 2016 at 15:31, Mark Lizar notifications@github.com wrote:

> Purpose Categories and PI Categories are required. THe suggestion in the
> past is to provide a list for the time being, but have other - as a
> categories so categories can be created by implementors. In the EU , the
> catagories of purpose also need to be harmonised across 28 countries and
> quite a few languages, so, this will most likely be a topic that will go on
> for a while and perhaps be addressed by ISO.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/KantaraInitiative/CISWG/issues/40#issuecomment-221070264

## 

This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. If you are not the intended recipient 
you are notified that disclosing, copying, distributing or taking any 
action in reliance on the contents of this information is strictly 
prohibited.

**Comment by PrivacyCDN** [comment]
Is this issue addressed by #42 and #43? If so can we close it?

**Comment by smartopian** [comment]
The issue here, PI, or PII - there  are a couple of fields in the spec that dont have just one definition.  ( or one set of purposes, or one set of attribute values, or one set of icons)  Its a common pattern.  I think at the root of this is the PI and PII definitions.   They may change on context and I am wondering if its possible to take an ' if this, then that approach '. 
As a suggestion, treating these fields as consent attributes,  For example the MVCR mode, would proscribe that Personally identifiable Information be captured on the receipt.  But that personal information, (not identifiable) which would cover IP address, cookies, trackers of any type, perhaps also meta-data related to individual. etc,   These could be added to the MVCR mode,  or fall under 'other' category - in as optional.  So, the guidance for the MVCR is that its for PII, but, the combination of purpose specification and sharing specification, may create additional PII that should be listed in the receipt, or in a policy linked to the receipt.

**Comment by PrivacyCDN** [comment]
For the purposes of the standard, we can and probably should define and
stick to one definition, PI or PII, I don’t care which. I suggest pointing
to the ISO definition of PII in the standard, but with this addition:
“Implementors of consent receipts should be aware that there are various
definitions of what information about a person is covered by various data
protection regimes. For the purposes of implementation implementors should
understand that any reference to PII in this document should be read to
include the definitions of such information that apply to the implementor.”

This gives us a baseline definition to work to for the purpose of
wordsmithing the standard, but makes clear that the standard recognizes
that that data protection regime that has jurisdiction over the implementor
has paramountcy.

From: Lizar Mark notifications@github.com notifications@github.com
Reply: KantaraInitiative/CISWG
reply@reply.github.com
reply@reply.github.com
Date: June 10, 2016 at 1:49:20 PM
To: KantaraInitiative/CISWG ciswg@noreply.github.com
ciswg@noreply.github.com
Cc: Wunderlich John john@wunderlich.ca john@wunderlich.ca, Mention
mention@noreply.github.com mention@noreply.github.com
Subject:  Re: [KantaraInitiative/CISWG] Listing Purposes for PI or PII : If
PI there are a lot more purposes to list (#40)

The issue here, PI, or PII - there are a couple of fields in the spec that
dont have just one definition. ( or one set of purposes, or one set of
attribute values, or one set of icons) Its a common pattern. I think at the
root of this is the PI and PII definitions. They may change on context and
I am wondering if its possible to take an ' if this, then that approach '.
As a suggestion, treating these fields as consent attributes, For example
the MVCR mode, would proscribe that Personally identifiable Information be
captured on the receipt. But that personal information, (not identifiable)
which would cover IP address, cookies, trackers of any type, perhaps also
meta-data related to individual. etc, These could be added to the MVCR
mode, or fall under 'other' category - in as optional. So, the guidance for
the MVCR is that its for PII, but, the combination of purpose specification
and sharing specification, may create additional PII that should be listed
in the receipt, or in a policy linked to the receipt.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
https://github.com/KantaraInitiative/CISWG/issues/40#issuecomment-225249714,
or mute the thread
https://github.com/notifications/unsubscribe/ADTJ9glT90X1Rya5Whm6hZJNYJfOXOIgks5qKaOggaJpZM4IJWfO
.

## 

This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. If you are not the intended recipient 
you are notified that disclosing, copying, distributing or taking any 
action in reliance on the contents of this information is strictly 
prohibited.

**Comment by maryhodder** [comment]
I thought we already discussed this months ago and agree to PI since PII
has a specific legal definition.

Also PII has a lot of issues, and so orgs like IDESG in our requirements or
others have used PI to get around the specific legal defs that have caused
problems.

**Comment by maryhodder** [comment]
Note also this:

The _Kantara Identity Assurance Framework - Glossary *doesn't have either
PI or PII.
It does have: *Identifier_
"Something that points to an individual, such as a name, a serial number,
or some other pointer to the party being identified."

Other defs we should consider using (only 1 though) and link to .. in our
glossary.

_Personal Information defs:_

_IDESG:_
"Any information about or linked to a USER that is collected, used,
transmitted, or stored in or by DIGITAL IDENTITY MANAGEMENT FUNCTIONS."
_ABA Identity Management Services Agreement_
"Personal information provided by a Subject to the Credential Service
Provider which is either (1) used by the Credential Service Provider in the
process of issuing the Credential, and/or (2) provided with the expectation
that the information will be transmitted to third parties to whom the
Subject presents the Credential."

_Generally Accepted Privacy Principles:  A Global Privacy Network_ "Information
that is or can be about or related to an identifiable individual."

_Personally identifiable information (PII) definitions:_

_E-Authentication Federation Interim Legal Document Suite_

"Any information that identifies or can be used to identify, contact, or
locate the person to whom such information pertains. This includes
information that is used in a way that is personally identifiable,
including linking it with identifiable information from other sources, or
from which other Personally Identifiable Information can easily be derived,
including, but not limited to, name, address, phone number, fax number,
email address, financial profiles, and social security number, and credit
card information."

_European Union eGovernment Unit: Modinis:  Common Terminological Framework
for Interop Electronic Identity Management_

"Personally identifiable information is any data that identifies or refers
to a particular natural or legal person."

_National Security Telecom Advisory Comm.(NSTAC) Report to the President on
Identity Management Strategy_

a. The information pertaining to any person which makes it possible to
identify such individual (including the information capable of identifying
a person when combined with other information even if the information does
not clearly identify the person). Note: Information that can be used to
identify an individual should be defined by national legislation.

b. Any information that identifies a person to any degree.

_Identity Management Task Force Report 2008_

"i. The information pertaining to any person which makes it possible to
identify such individual (including the

information capable of identifying a person when combined with other
information even if the information does not clearly identify the person).
Note: Information that can be used to identify an individual should be
defined by national legislation.

ii. Any information which identifies a person to any degree."

_Liberty Alliance Privacy and Security Best Practices_

"Any data that identifies or locates a particular person, consisting
primarily of name, address, telephone number, e-mail address, bank
accounts, or other unique identifiers such as Social Security numbers. "

_Liberty Glossary v.2.0_

_"_Any data that identifies or locates a particular person, consisting
primarily of name, address, telephone number, e-mail address, bank
accounts, or other unique identifiers such as Social Security numbers."

_International Telecommunications Union (ITU)_

"The information pertaining to any living person which makes it possible to
identify such individual (including the information capable of identifying
a person when combined with other information even if the information does
not clearly identify the person)."

_ITU-T X.1252 Baseline Identity Management Terms and Definitions_

"Any information (a) that identifies or can be used to identify, contact,
or locate the person to whom such information pertains, (b) from which
identification or contact information of an individual person can be
derived, or (c) that is or can be linked to a natural person directly or
indirectly."

**Comment by smartopian** [comment]
Again,, 

the issue I am trying to raise here is not that their are multiple definitions of PI or PII, (which there are) its a functional issue in that some PI once added to the receipt becomes PII. 
1. Listing PI, includes many other data types which would make a big list and is a lot harder  to assess  and create a consent receipt for. 
2. Listing PII creates a much smaller list to begin with (makes much better consent receipts) 

(its a functional implementation issue) not a terminology issue. 

as a result, I am proposing that we start with the smaller PII list when creating a receipt,  then, assess if adding PI or if combining PI with a receipt would turn  PI into additional PII. So that PI can be added at the implementor’s discretion.  

For example: if IP address is added to Location and Contact then the IP address becomes PII and should/could be listed as PII on the receipt. 

The common approach being: 

(If this PI, is added to that PI (or PII) on a receipt, then, PI=PII and should/must be listed)

**Comment by smartopian** [comment]
Personal Information definitions around the world.

Personal Information, Personal Data and Personally Identifiable Information are variously and more or less equivalently defined as follows (references are hyperlinked in the names of each country):

United Kingdom

data which relate to a living individual who can be identified

Germany

any information concerning the personal or material circumstances of an identified or identifiable individual

Canada

information about an identifiable individual

United States

information which can be used to distinguish or trace an individual's identity ...

Australia

information or an opinion ... about an identified individual, or an individual who is reasonably identifiable.

**Comment by maryhodder** [comment]
My point is, definitionally, there is little difference between PII and PI
as used in many different specs and documents by our brethren.

Let's pick one --  decide on PI or PII (my vote is PI so we aren't held to
the legal defs in some jurisdictions where it gets messy) and then use a
definition that is already standardized and link back to it.

I shared those examples so we could do that. Will copy them into the
spreadsheet and Thursday we can go through and pick one.

**Comment by maryhodder** [comment]
Cool.. do you know where these come from mark? Not just "country" but
actual document and standard?

**Comment by smartopian** [comment]
First, we have made the decision a long time ago to use ISO 29100 as a basis for terminology.  .

Second, I may be  describing this badly, as it seems the point of this ticket is not being understood.  The point being made is raised from the Kantara Implementation 

—>  because the feedback from the Kantara Implementation is, that when making an initial list of purpose and sharing specifications for listing in a receipt  - PII is a much more narrow and easier set of requirements to start with when listing purpose, as listing all possible PI in the consent receipt is onerous conformance requirements to start with.  

Adding and listing all attributes that can be personal information related to the consent can be much more difficult and might present a barrier to adoption if this was required.  i.e. cookies, IP address, and third party tracking of non-identified shared data.   

FYI - Here is The ISO definition for  PII, 
(personally identifiable information)
“2.10 PII: any information (a) that can be used to identify the person to whom such information pertains, (b) from which such information can be derived, or (c) that is or might be directly or indirectly linked to a natural person."

This is different that the issue which was raised,

 The solution suggested here is to use this ISO PII definition for the receipt, and note (As a piece of guidance. )  that PI can also be added (listed) to the receipt with the aim, to keep the spec minimal to start with and expand to the maximal, depending on  implementors requirements

FYI- this is also a good topic to also be addressed in the UX, icons and third party frameworks sections of the spec, i.e. a bunch of PI and permissions packed into one icon (i.e user submitted terms) 

I have a list of references for consent being compiled here:
https://docs.google.com/spreadsheets/d/1Oo2qiWrbbgAiVuRHrRAkx5GQc6UdfuFDdEbNSUcIt0Q/edit?usp=sharing https://docs.google.com/spreadsheets/d/1Oo2qiWrbbgAiVuRHrRAkx5GQc6UdfuFDdEbNSUcIt0Q/edit?usp=sharing

**Comment by PrivacyCDN** [comment]
Thanks for reminding us that this is a settled issue for the standard. PI
it is.

Sincerely,
John Wunderlich
@PrivacyCDN

Call: +1 (647) 669-4749
eMail: john@wunderlich.ca

On 10 June 2016 at 18:00, maryhodder notifications@github.com wrote:

> I thought we already discussed this months ago and agree to PI since PII
> has a specific legal definition.
> 
> Also PII has a lot of issues, and so orgs like IDESG in our requirements or
> others have used PI to get around the specific legal defs that have caused
> problems.
> 
> On Fri, Jun 10, 2016 at 3:52 PM, John Wunderlich <notifications@github.com
> 
> > wrote:
> > 
> > For the purposes of the standard, we can and probably should define and
> > stick to one definition, PI or PII, I don’t care which. I suggest
> > pointing
> > to the ISO definition of PII in the standard, but with this addition:
> > “Implementors of consent receipts should be aware that there are various
> > definitions of what information about a person is covered by various data
> > protection regimes. For the purposes of implementation implementors
> > should
> > understand that any reference to PII in this document should be read to
> > include the definitions of such information that apply to the
> > implementor.”
> > 
> > This gives us a baseline definition to work to for the purpose of
> > wordsmithing the standard, but makes clear that the standard recognizes
> > that that data protection regime that has jurisdiction over the
> > implementor
> > has paramountcy.
> > 
> > From: Lizar Mark notifications@github.com notifications@github.com
> > Reply: KantaraInitiative/CISWG
> > reply@reply.github.com
> > reply@reply.github.com
> > Date: June 10, 2016 at 1:49:20 PM
> > To: KantaraInitiative/CISWG ciswg@noreply.github.com
> > ciswg@noreply.github.com
> > Cc: Wunderlich John john@wunderlich.ca john@wunderlich.ca, Mention
> > mention@noreply.github.com mention@noreply.github.com
> > Subject: Re: [KantaraInitiative/CISWG] Listing Purposes for PI or PII :
> > If
> > PI there are a lot more purposes to list (#40)
> > 
> > The issue here, PI, or PII - there are a couple of fields in the spec
> > that
> > dont have just one definition. ( or one set of purposes, or one set of
> > attribute values, or one set of icons) Its a common pattern. I think at
> > the
> > root of this is the PI and PII definitions. They may change on context
> > and
> > I am wondering if its possible to take an ' if this, then that approach
> > '.
> > As a suggestion, treating these fields as consent attributes, For example
> > the MVCR mode, would proscribe that Personally identifiable Information
> > be
> > captured on the receipt. But that personal information, (not
> > identifiable)
> > which would cover IP address, cookies, trackers of any type, perhaps also
> > meta-data related to individual. etc, These could be added to the MVCR
> > mode, or fall under 'other' category - in as optional. So, the guidance
> > for
> > the MVCR is that its for PII, but, the combination of purpose
> > specification
> > and sharing specification, may create additional PII that should be
> > listed
> > in the receipt, or in a policy linked to the receipt.
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > <
> > 
> > https://github.com/KantaraInitiative/CISWG/issues/40#issuecomment-225249714
> > 
> > > ,
> > > or mute the thread
> > > <
> > 
> > https://github.com/notifications/unsubscribe/ADTJ9glT90X1Rya5Whm6hZJNYJfOXOIgks5qKaOggaJpZM4IJWfO
> > 
> > > .
> > 
> > ## 
> > 
> > This email and any files transmitted with it are confidential and
> > intended
> > solely for the use of the individual or entity to whom they are
> > addressed.
> > If you have received this email in error please notify the system
> > manager.
> > This message contains confidential information and is intended only for
> > the
> > individual named. If you are not the named addressee you should not
> > disseminate, distribute or copy this e-mail. Please notify the sender
> > immediately by e-mail if you have received this e-mail by mistake and
> > delete this e-mail from your system. If you are not the intended
> > recipient
> > you are notified that disclosing, copying, distributing or taking any
> > action in reliance on the contents of this information is strictly
> > prohibited.
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > <
> > https://github.com/KantaraInitiative/CISWG/issues/40#issuecomment-225292698
> > ,
> > or mute the thread
> > <
> > https://github.com/notifications/unsubscribe/ACGyUKXZYxUX2RT7V3AlFx8YkelCV6hxks5qKc6ZgaJpZM4IJWfO
> > 
> > .
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/KantaraInitiative/CISWG/issues/40#issuecomment-225306533,
> or mute the thread
> https://github.com/notifications/unsubscribe/ADTJ9oQ1Hn4CSgBaGUOIDsvVE46kfvi6ks5qKd6LgaJpZM4IJWfO
> .

## 

This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. If you are not the intended recipient 
you are notified that disclosing, copying, distributing or taking any 
action in reliance on the contents of this information is strictly 
prohibited.

**Comment by maryhodder** [comment]
Ok.. I thought we were using definitions and descriptions for the language
in the spec. I didn't realize that you thought a descriptive word drove the
content in the fields. PI and PII, in our review this spring for another
group, led us to conclude they are effectively the same across many specs,
jurisdictions and standards, but PII comes with legal definitions we didn't
want to attach our work to and have govern.

If you want to use PII that's fine, but the definitions and what falls
under it, as PII verses PI are actually the same.

Using PII to describe it doesn't get you a shorter list in my view. The
list of possible data that falls under it is exactly the same.

As for deciding, I guess I missed the meeting the past two months where
that decision was made, as when you asked me 2 months ago about PI v. PII,
and I explained this issue, you said it wasn't yet decided.

But if the group decided to use PII and take on the legal side of that,
that's fine.

**Comment by smartopian** [comment]
Ok .. so -- as this  is an implementation issue (see label) it needs a response more like:  

What do you think of: 

 MUST record PII sharing on a receipt and MAY list PI, relevant to the consent transaction in the consent receipt, i.e - session only cookies, IP addresses, 3rd Party Analytics etc.

**Comment by smartopian** [comment]
resolved in implementation
