### ISSUE TITLE
Creating a Purpose Listing

### ISSUE THREAD

**Issue by smartopian** [KantaraInitiative/CISWG#42]
Was interesting issue that came up on call yesterday.    The assumption was their was an agreement that a bunch of the field names in the spec are used to create a purpose listing, rather that the purpose field being backed with multiple requirements which instruct on how to create a purpose listing. 

As well, the idea that the individual provides consent for each purpose , was challenged with the idea that  all of the purposes in a receipt comprise 1 consent. 

In the work input created so far, the specification is proposed as a way to create a granular consent receipt 
For example (see this screen shot) where fields are used as single fields for one purpose, and that each purpose has its own consent type,  so a consent receipt can hold multiple consents.  

I propose we ratify this understanding of granular consent specification, with mulitiple consents possible per receipt. 

This would include, service name, purpose description, purpose category, PI categories, etc, all are used to create a purpose listing.   (if others have a different understanding please outline these and counter propose) 

![purpose-listing](https://cloud.githubusercontent.com/assets/6548199/15503267/e3821f52-21b0-11e6-8d72-192fb949e7f9.png)

**Comment by smartopian** [comment]
In addition to the above, and in the Kantara Implementation it may be useful to split sharing (y/N) into 2 fields : Sharing (Y/N) - How its shared -  I.e. Sharing = Y  How = Publically,  
Like wise for 3rd Party Sharing  - not how but  3rd Party Sharing PI Category could also be added as an extra field 
For Example:  3rd Party Sharing = Y,  Sharing PI Category = Contact 
(of course this comment is dependant on the issue above being ratified)

**Comment by PrivacyCDN** [comment]
Each of these will need discussion on the calls to work towards consensus.
This is a net new proposal, not exactly representing what I heard in the
call. I do recall being tasked with a takeaway to develop a representation
of the version of the Purpose field as list that we discussed. If we can
park this proposal as an issue while I work on what came out of the call it
may help us stay focussed on getting v 1.0 out the door more quickly.

JW

Sincerely,
John Wunderlich
@PrivacyCDN

Call: +1 (647) 669-4749
eMail: john@wunderlich.ca

On 24 May 2016 at 07:59, Mark Lizar notifications@github.com wrote:

> Was interesting issue that came up on call yesterday. The assumption was
> their was an agreement that a bunch of the field names in the spec are used
> to create a purpose listing, rather that the purpose field being backed
> with multiple requirements which instruct on how to create a purpose
> listing.
> 
> As well, the idea that the individual provides consent for each purpose ,
> was challenged with the idea that all of the purposes in a receipt comprise
> 1 consent.
> 
> In the work input created so far, the specification is proposed as a way
> to create a granular consent receipt
> For example (see this screen shot) where fields are used as single fields
> for one purpose, and that each purpose has its own consent type, so a
> consent receipt can hold multiple consents.
> 
> I propose we ratify this understanding of granular consent specification,
> with mulitiple consents possible per receipt.
> 
> This would include, service name, purpose description, purpose category,
> PI categories, etc, all are used to create a purpose listing. (if others
> have a different understanding please outline these and counter propose)
> 
> [image: screen shot 2016-05-24 at 12 56 02]
> https://cloud.githubusercontent.com/assets/6548199/15502956/f262d0ea-21ae-11e6-933c-c487665c3519.png
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/KantaraInitiative/CISWG/issues/42

## 

This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. If you are not the intended recipient 
you are notified that disclosing, copying, distributing or taking any 
action in reliance on the contents of this information is strictly 
prohibited.

**Comment by smartopian** [comment]
The quick way is to not  do anything new with purpose fields,  and keep what Iain has put forward as the must fields, not  adding new fields, and get this out..  Time is up. basically,

**Comment by smartopian** [comment]
even though time is up,, I would be really interested in hearing what your idea is for purpose listing.  especially if you had a break through, apologies if I may have stifled you in this regard.

**Comment by PrivacyCDN** [comment]
Can issue #42 and #43 be merged? They appear to be on the same topic and I suspect a resolution of one will resolve both.

**Comment by maryhodder** [comment]
Resolved, we are using Purpose Category in the field table.
