### ISSUE TITLE
In the Charter we have the requirement of selecting an SDO, but Kantara is now an SDO

### ISSUE THREAD

**Issue by smartopian** [KantaraInitiative/CISWG#5]
Should we change the charter and put kantara as SDO for these specifications?

**Comment by PrivacyCDN** [comment]
I don't think I know enough about what an SDO is in relation to Kantara and
the Consent Receipt and what the implications are to answer that question.

Sincerely,
John Wunderlich
@PrivacyCDN

Call: +1 (647) 669-4749
eMail: john@wunderlich.ca

On 8 February 2016 at 17:26, Mark Lizar notifications@github.com wrote:

> Should we change the charter and put kantara as SDO for these
> specifications?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/KantaraInitiative/CISWG/issues/5.

## 

This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. If you are not the intended recipient 
you are notified that disclosing, copying, distributing or taking any 
action in reliance on the contents of this information is strictly 
prohibited.

**Comment by smartopian** [comment]
Moving the project on to an SDO is no longer a requirement as per the new charter.  Kantara CISWG is now the SDO.  (issue closed)
