### ISSUE TITLE
Use Cases in Work Book aren't actually use cases

### ISSUE THREAD

**Issue by PrivacyCDN** [KantaraInitiative/CISWG#56]
I've reviewed the tab in the work book labelled use cases and find that while some of the rows may represent a use case or an aspect of a use case, some are are issues and not actually use cases. For example, row 9 labelled "Trust Consent Transparency" is an issue, not a use case. Similarly, row 6 asks the question of how a consent receipt maps to ISO 29100. This is not a use case.

This suggests that we need to devote some time in a call identifying the core use cases and moving the non-use case items to the issues list where they can be dealt with appropriately. I'm working on a use case [document ](https://docs.google.com/a/wunderlich.ca/document/d/1ArpMvubAwyGfYVukOBsI_X9T7jOc5h4snOaK3xSSsqs/edit?usp=sharing) to show what I mean for what I believe to be our basic use case: Basic Web Site Registration. This is the case where Alice provides information about herself to Bob's web site for the purpose of registering as a user on the web site. 

Interestingly, writing this use case made clear to me the utility of Eve's suggestions for conformance modes. It is proving relatively trivial to write this use case to include both conformance mode 1 and conformance mode 2 event flows. But the explicit writing of those flows should prove useful for implementors.

**Comment by smartopian** [comment]
Hi, 

Yes - the use cases do need to be cleaned up and defined. (its in progress) 

There is already a space on the wiki for it

https://kantarainitiative.org/confluence/display/infosharing/MVCR+-+Alice+Gives+Consent+to+Bob.co?src=contextnavchildmode https://kantarainitiative.org/confluence/display/infosharing/MVCR+-+Alice+Gives+Consent+to+Bob.co?src=contextnavchildmode 

so, the Kantara Implementation would be an example of this?

**Comment by PrivacyCDN** [comment]
OK, moved the draft use case to Kantara at
https://kantarainitiative.org/confluence/display/infosharing/Use+Case%3A+Basic+Site+Registration?src=contextnavchildmode

Sincerely,
John Wunderlich
@PrivacyCDN

Call: +1 (647) 669-4749
eMail: john@wunderlich.ca

On 28 June 2016 at 13:21, Mark Lizar notifications@github.com wrote:

> Hi,
> 
> Yes - the use cases do need to be cleaned up and defined. (its in
> progress)
> 
> There is already a space on the wiki for it
> 
> https://kantarainitiative.org/confluence/display/infosharing/MVCR+-+Alice+Gives+Consent+to+Bob.co?src=contextnavchildmode
> <
> https://kantarainitiative.org/confluence/display/infosharing/MVCR+-+Alice+Gives+Consent+to+Bob.co?src=contextnavchildmode>
> 
> so, the Kantara Implementation would be an example of this?
> 
> > On 28 Jun 2016, at 13:07, John Wunderlich notifications@github.com
> > wrote:
> > 
> > I've reviewed the tab in the work book labelled use cases and find that
> > while some of the rows may represent a use case or an aspect of a use case,
> > some are are issues and not actually use cases. For example, row 9 labelled
> > "Trust Consent Transparency" is an issue, not a use case. Similarly, row 6
> > asks the question of how a consent receipt maps to ISO 29100. This is not a
> > use case.
> > 
> > This suggests that we need to devote some time in a call identifying the
> > core use cases and moving the non-use case items to the issues list where
> > they can be dealt with appropriately. I'm working on a use case document <
> > https://docs.google.com/a/wunderlich.ca/document/d/1ArpMvubAwyGfYVukOBsI_X9T7jOc5h4snOaK3xSSsqs/edit?usp=sharing>to
> > show what I mean for what I believe to be our basic use case: Basic Web
> > Site Registration. This is the case where Alice provides information about
> > herself to Bob's web site for the purpose of registering as a user on the
> > web site.
> > 
> > Interestingly, writing this use case made clear to me the utility of
> > Eve's suggestions for conformance modes. It is proving relatively trivial
> > to write this use case to include both conformance mode 1 and conformance
> > mode 2 event flows. But the explicit writing of those flows should prove
> > useful for implementors.
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub <
> > https://github.com/KantaraInitiative/CISWG/issues/56>, or mute the thread
> > <
> > https://github.com/notifications/unsubscribe/AGPq5-FQu_-Hm-AohcW8i55eIDWrmEpXks5qQVS1gaJpZM4JAUj8
> > .
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/KantaraInitiative/CISWG/issues/56#issuecomment-229118953,
> or mute the thread
> https://github.com/notifications/unsubscribe/ADTJ9roqeipe0r01Bxa0ZkeodMOlcU5Aks5qQVgNgaJpZM4JAUj8
> .

## 

This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. If you are not the intended recipient 
you are notified that disclosing, copying, distributing or taking any 
action in reliance on the contents of this information is strictly 
prohibited.

**Comment by iainh1** [comment]
That’s very useful thanks John, that use case format is great.

So what other use cases should we document in the same format?

Cheers

Iain

**Comment by PrivacyCDN** [comment]
Iain;
The format is grounded in a number of standard use case templates that I've seen or used. It doesn't have a detailed 'user story' which might be useful for context but that is superfluous for setting out what we need. There is also still room to add more details, consideration and guidance to or as supplements to the basic use case. In addition, we should consider adding variants within or supplemental to the basic site registration use case. It is the case that this use case is based on Alice providing consent after entering her PII. But what about the case where the bulk of the PII will be collected after registration. Examples includes any service that authorized future collections of PII based on the initial registration - Fitbit or any fitness app for example will not only collect health and location data but will make inferences about Alice's PII that she may not have anticipated.
As for your question, if the format is acceptable to the rest of the group, we should probably start by updating the other three items in the use case space:
1. Alice explicitly shares PI2. Kantara Implementation Use Case3. MVCR: Alive gives consent to Bob.co
#3 is just a sequence diagram. It should be added to the Basic Site Registration Use Case and then deleted.#2 appears to be a pilot of the basic use case, and the experience that has been derived from it  could be used to add depth to the basic use case. The details of the pilot itself should be moved out of 'use cases' and put in a different space, maybe grouped as "Implementation Examples".#1 is unclear. I think it provides information intended to help determine what the required fields should be in a CR, and is therefore not actually a use case. Should be discussed by the group.
It seems to me that we do need use cases for:
1. CR Updates: Bob updates his privacy policy and therefore needs to update Alice's CR. There will be a number of variations of this including new purposes, new regulations, new uses, new disclosures etc...
2. CR Management: Use case(s) to set out what consent management functionality using Mode 2 would perform for  A. Alice B. Bob C. Third parties and/or data processors receiving Alice's information from Bob.
John Wunderlich,

Sent frum a mobile device,
Pleez 4give speling erurz

"...a world of near-total surveillance and endless record-keeping is likely to be one with less liberty, less experimentation, and certainly far less joy..." A. Michael Froomkin

```
    _____________________________
```

**Comment by smartopian** [comment]
I think making a template is a bit over perscriptive.  I really like the UMA approach.

https://kantarainitiative.org/confluence/display/uma/UMA+Scenarios+and+Use+Cases

**Comment by smartopian** [comment]
but templates are helpful..  thanks !  --  some use cases ARE JUST pieces of Use Cases.
