### ISSUE TITLE
Time stamp timezone

### ISSUE THREAD

**Issue by dturnerx** [KantaraInitiative/CISWG#63]
Consent Timestamp': recommend you standardise this to UTC to simplify implementation and interoperability.

Issue 1: the data storage format shall be specified in UTC time zone
Issue 2: usability and display formats shall be considered when displaying information to people
Issue 3: should there be 2 fields - one for the UTC time and another for the 'localized' time which includes the timezone?

**Comment by dturnerx** [comment]
I recommend the use of ISO8601 for all date and time fields https://en.wikipedia.org/wiki/ISO_8601

**Comment by PrivacyCDN** [comment]
👍🏻

Thanks, John
4giv spellin errurz from mobile devize
________________________________
