### ISSUE TITLE
Add  time element of consent

### ISSUE THREAD

**Issue by dturnerx** [KantaraInitiative/CISWG#69]
e.g. access for 30 minutes, for one month, one year, 3 months in perpetuity etc..

**Comment by dturnerx** [comment]
Would "duration" be a better label? 

If adopted, this field should be "text" because anything else will be too complex.

**Comment by PrivacyCDN** [comment]
Not convinced that any duration or termination tine is necessary outside of a specific profile.

Thanks, John
4giv spellin errurz from mobile devize
________________________________
