### ISSUE TITLE
Add frequency of access

### ISSUE THREAD

**Issue by dturnerx** [KantaraInitiative/CISWG#70]
e.g. once a month, up to five time

**Comment by dturnerx** [comment]
Are there known use cases for this field? 

If adopted, this field should be "text" because anything else will be too complex.

**Comment by PrivacyCDN** [comment]
Punt to a profile if/when we regularize profiles.

Thanks, John
4giv spellin errurz from mobile devize
________________________________

**Comment by dturnerx** [comment]
2017-08-03 conf call agreed to push this to a profile.
