### ISSUE TITLE
Security Considerations section

### ISSUE THREAD

**Issue by dturnerx** [KantaraInitiative/CISWG#83]
General concern: no real consideration is given in this document to security requirements. I strongly urge that you consider recommending that receipts are signed - i.e. as a JWS - to mitigate the risk of a forged receipt; or - in the case of someone relying on a receipt in the context of a legal action, the defence that the receipt *might* have been forged or otherwise altered after issuance. I also strongly urge that consent receipts be encrypted, to protect PII; or, at the very least, that you require receipts to be transmitted via a secure channel.

**Comment by PrivacyCDN** [comment]
In the course of discussions, I recall saying that the security of the transport vis-a-vis the receipt is an implementation consideration, although noting that the consent receipt should not have less security than the transaction it records.

**Comment by IDmachines** [comment]
+1

**Comment by TomCJones** [comment]
I don't understand the concept "security than the transaction it records". The consent receipt may happen very early in an interchange, way before a transactions (meaning commitment of resources) occurs. There is, as a general case, no way for an RP to understand the level of security required until the user's requirements are more full known.

**Comment by dturnerx** [comment]
done - DRAFT 5 https://kantarainitiative.org/confluence/download/attachments/76447870/Consent%20Receipt%20Specification%201_1_0%20DRAFT%205a.docx?version=1&modificationDate=1508987029000&api=v2
