### ISSUE TITLE
Add detail to purposes list

### ISSUE THREAD

**Issue by dturnerx** [KantaraInitiative/CISWG#88]
Jim Fournier also suggests that the purposes should be defined in more granular detail at a linked table and that “marketing” is too vague to serve as a meaningful purpose.

**Comment by smartopian** [comment]
I think there is confusion  between specifying a ' purpose category' and 'describing a purpose' .

For example:
It is proposed that in the consent receipt first a purpose category is selected, then a purpose sub-category, then a purpose description based on that subcategory.  
 
For legacy practices this would look like. 
 
I (enter name) consent to marketing for services I use already, specifically;  X service to send me direct marketing using (PII Category) email address. 
 
In machine readable or a record this would be a selection of a purpose category and a subcategory, with a text field providing more granular description. 
 
For a human readable receipt made from a machine readable record of consent.  This would appear as a single layer summary (or iconic summary) of a privacy policy relevant to the PII Principle which links to the record of consent for more information. 

[Purpose Category][Purpose Sub-Cat][Core Purpose Y/N][PurposeDescription]

**Comment by PrivacyCDN** [comment]
See my comment on Issue #96 Each stated purposes should be a stand alone statement that provides sufficient detail to explain what personal data is being used for that purpose.

"We collect information about you for the purpose of physically delivering our product to you." might be a simple example.

**Comment by dturnerx** [comment]
WG agreed to move this to an external document
